### ISSUE TITLE
Footer links not opening in a new tab

### ISSUE THREAD

**Issue by amlan-roy** [amlan-roy/resume-craft#29]
**Describe the bug**

The footer links (GitHub, portfolio etc) do not open in a new tab

**Proposed solution**
Add `target="_blank"` in the footer links.

**Are you willing to contribute to this issue?**
Yes

**Comment by avi-l** [comment]
PR: https://github.com/amlan-roy/resume-craft/pull/30

**Comment by amlan-roy** [comment]
Thanks for the effort @avi-l
