### ISSUE TITLE
HTML and footer update

### ISSUE THREAD

**Issue by amlan-roy** [amlan-roy/resume-craft#48]
## Is your feature request related to a problem? Please describe.

Issues:
- The layout files have `<Header>` and `<Footer>` elements inside `<main>`, but we want the structure to be `<><Header /><main>{children}</main><Footer /></>` instead.
- The footer is fixed at bottom of viewport and overlaps the other elements. We want them to be at the bottom of the whole page, not fixed to the bottom of the viewport.

## Suggestions
Run the repo locally by running `npm run dev`

- the the layout.tsx files (except `src\app\layout.tsx`), should have the following structure
```
<>
   <Header />
   <main className="flex-grow">{children}</main>
   <Footer />
 </>
```
- In the `src\app\layout.tsx` file, add `min-height: 100vh`, `display: flex` and `flex-direction: column` tailwind classes
- Remove `fixed bottom-0 left-0 right-0` from footer (in `src\components\global\Footer.tsx)

## Are you willing to contribute to this issue?

Yes, but help is always welcomed

## Additional Details

Test all the routes to see if the UI is working as expected
Routes to check:
- http://localhost:3000/
- http://localhost:3000/home
- http://localhost:3000/generate-resume/base

**Comment by tusharwebd** [comment]
Hi @amlan-roy! New contributor here and I would be interested to work on this. Let me know if I can pick this up.

**Comment by amlan-roy** [comment]
> Hi @amlan-roy! New contributor here and I would be interested to work on this. Let me know if I can pick this up. 

@tusharwebd: Sure. You can go ahead and assign the issue to yourself. Thanks.

**Comment by tusharwebd** [comment]
I believe only repo owners can assign the issue. So feel free to assign this to me. I'll start working on issue in the meanwhile.

**Comment by amlan-roy** [comment]
@tusharwebd : Updated the issue description a bit to be more clear about the requirements.

**Comment by tusharwebd** [comment]
Thanks for the suggestions as well! I've made the required fix in this PR: https://github.com/amlan-roy/resume-craft/pull/52.

**Comment by amlan-roy** [comment]
Merged the PR. Thanks for the efforts @tusharwebd!
